{{- if .Values.splunk.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ printf "%s-secret-manager" (include "logging-config.fullname" .) | trunc 63 }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging-config.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
{{- end }}

