{{- if .Values.splunk.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "logging-config.fullname" . }}-splunk-hec-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging-config.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.splunk.refreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: {{ printf "%s-secret-manager" (include "logging-config.fullname" .) | trunc 63 }}
  target:
    name: {{ printf "%s-%s" (include "logging-config.fullname" .) .Values.splunk.hecTokenSecretName | trunc 63 }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: SplunkHecToken
    remoteRef:
      key: {{ printf "/datajar/%s/portal/secrets" .Values.environmentName }}
      property: splunk-hec-token
{{- end }}

